### ISSUE TITLE
Winforms Sample Needed

### ISSUE THREAD

**Issue by larsontim12** [weikio/PluginFramework#21]
Please add a winforms sample when you can.

Looks great!!
Tim

**Comment by mikoskinen** [comment]
Thank you for the comment! Yes, this is indeed currently missing and needs to be added.

**Comment by mikoskinen** [comment]
There's now a Windows Forms (.NET Core) sample available from https://github.com/weikio/PluginFramework/tree/master/samples/WinFormsApp

It mainly mimics the WPF-sample but also shows couple other features.

Note: The following code is currently needed in Program.cs:

```            PluginLoadContextOptions.Defaults.AdditionalRuntimePaths.Add(Path.GetDirectoryName(typeof(Button).Assembly.Location));
```

Otherwise Plugin Framework can't locate the WinForm dlls referenced by the plugins. We should be able to make Plugin Framework automatically handle this scenario, I'll open an another ticket for that.

**Comment by larsontim12** [comment]
Works great!  Thanks for the quick response on getting the sample done!
